// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj4bo7jQbQ6ftzVpNTvUXnO-5n0ZV5gjI',
    appId: '1:14004352245:web:7338d8d5ac3a68780a81bc',
    messagingSenderId: '14004352245',
    projectId: 'travel-blog-83da4',
    authDomain: 'travel-blog-83da4.firebaseapp.com',
    storageBucket: 'travel-blog-83da4.firebasestorage.app',
    measurementId: 'G-7BMDK4T22W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqC6onYtfDkmV2nOpE0jSxXCy0o5LzuWk',
    appId: '1:14004352245:android:8bc9214543155a2e0a81bc',
    messagingSenderId: '14004352245',
    projectId: 'travel-blog-83da4',
    storageBucket: 'travel-blog-83da4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdHL1cFBXW7jKsdbbVdtQ5BHb6QjWb-FQ',
    appId: '1:14004352245:ios:c4a5c9addeec37c00a81bc',
    messagingSenderId: '14004352245',
    projectId: 'travel-blog-83da4',
    storageBucket: 'travel-blog-83da4.firebasestorage.app',
    iosBundleId: 'com.example.fcuTravelBlogFixed2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdHL1cFBXW7jKsdbbVdtQ5BHb6QjWb-FQ',
    appId: '1:14004352245:ios:c4a5c9addeec37c00a81bc',
    messagingSenderId: '14004352245',
    projectId: 'travel-blog-83da4',
    storageBucket: 'travel-blog-83da4.firebasestorage.app',
    iosBundleId: 'com.example.fcuTravelBlogFixed2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj4bo7jQbQ6ftzVpNTvUXnO-5n0ZV5gjI',
    appId: '1:14004352245:web:6fe9b4274fd714180a81bc',
    messagingSenderId: '14004352245',
    projectId: 'travel-blog-83da4',
    authDomain: 'travel-blog-83da4.firebaseapp.com',
    storageBucket: 'travel-blog-83da4.firebasestorage.app',
    measurementId: 'G-RFLQGT048M',
  );
}
